// src/routes/home/components/edit-sleep-session-dialog/edit-sleep-session-dialog.tsx
import { Dialog } from "../../../../components/dialog/dialog";
import { SleepSessionRecord } from "../session-records/session-records";

interface EditSleepSessionDialogProps {
    isOpen: boolean
    onClose: () => void,
    record: SleepSessionRecord | null
}

export function EditSleepSessionDialog(props: EditSleepSessionDialogProps) {
    return (
        <Dialog isOpen={props.isOpen}>
            <div>
                <h1 className="text-xl font-semibold dark:text-gray-100">Sleep session</h1>

                <div className="flex flex-col gap-4 mt-8">
                    <div className="flex gap-4">
                        <div className="flex grow flex-col gap-2">
                            <label htmlFor="in-bed-at" className="dark:text-gray-100">In bed at</label>
                            <input id="in-bed-at" type="datetime-local" className="px-4 py-2 rounded-xl border border-gray-100 dark:border-gray-500 bg-transparent dark:text-gray-100" />
                        </div>

                        <div className="flex grow flex-col gap-2">
                            <label htmlFor="woke-up-at" className="dark:text-gray-100">Woke up at</label>
                            <input id="woke-up-at" type="datetime-local" className="px-4 py-2 rounded-xl border border-gray-100 dark:border-gray-500 bg-transparent dark:text-gray-100" />
                        </div>
                    </div>

                    <div className="flex gap-2 items-center">
                        <label htmlFor="nap" className="dark:text-gray-100">Nap?</label>
                        <input id="nap" type="checkbox" />
                    </div>
                </div>


                <div className="flex items-center gap-2 justify-end mt-8">
                    <button className="px-4 py-2 rounded-full dark:text-gray-100" onClick={props.onClose}>
                        Close
                    </button>

                    <button className="px-4 py-2 rounded-full border-2 border-blue-500 dark:text-gray-100" onClick={props.onClose}>
                        Create
                    </button>
                </div>
            </div>
        </Dialog>
    )
}

// src/routes/(authenticated)/history/components/edit-sleep-session-dialog.svelte
<script lang="ts">
	import Dialog from '../../../../components/dialog.svelte';
	import { createEventDispatcher } from 'svelte';
	export let isOpen = false;

	let dispatch = createEventDispatcher();

	function handleClose() {
		dispatch('close');
	}
</script>

<Dialog title="Edit sleep session" {isOpen} on:close={handleClose}>
	<div slot="body" class="flex flex-col gap-4 my-4">
		<div>
			<label for="in-bed-at">In bed at</label>
			<input
				id="in-bed-at"
				class="rounded-lg bg-slate-700 px-4 py-2 w-full"
				type="datetime-local"
			/>
		</div>

		<div>
			<label for="woke-up-at">Woke up at</label>
			<input
				id="woke-up-at"
				class="rounded-lg bg-slate-700 px-4 py-2 w-full"
				type="datetime-local"
			/>
		</div>

		<div class="flex gap-2 items-center">
			<label for="nap">Is it napping?</label>
			<input id="nap" type="checkbox" />
		</div>
	</div>
	<div slot="footer">
		<button class="px-4 py-2 text-slate-100" on:click={handleClose}> Close </button>
		<button
			class="px-4 py-2 bg-sky-500 rounded-full text-slate-100 font-semibold"
			on:click={handleClose}>Update</button
		>
	</div>
</Dialog>
