// src/components/dialog/dialog.tsx
import { ReactPortal } from "../portal/portal";

interface DialogProps {
    isOpen: boolean,
    children: JSX.Element
}

export function Dialog(props: DialogProps) {
    if (props.isOpen === false) {
        return null
    }

    return (
        <ReactPortal id="dialog">
            <div style={{ backdropFilter: 'blur(1px)' }} className="flex justify-center items-center bg-zinc-900/20 fixed top-0 left-0 right-0 bottom-0">
                <div className="bg-black drop-shadow-lg max-w-screen-sm w-full rounded-2xl p-4 m-4">
                    {props.children}
                </div>
            </div>
        </ReactPortal>
    )
}

// src/components/dialog.svelte
<script lang="ts">
	import clickOutside from '../helpers/click-outside';
	import { createEventDispatcher } from 'svelte';
	import focusTrap from '../helpers/focus-trap';

	export let title: String;
	export let isOpen = false;

	const dispatch = createEventDispatcher();

	function handleClose() {
		dispatch('close');
	}

	function handleKeyDown(event: KeyboardEvent): void {
		if (event.code === 'Escape') {
			handleClose();
		}
	}
</script>

{#if isOpen}
	<div
		use:focusTrap
		class="flex justify-center items-center absolute top-0 right-0 left-0 bottom-0 bg-black/70"
		on:keydown={handleKeyDown}
	>
		<div
			class="max-w-screen-sm w-full bg-slate-800 p-4 rounded-lg drop-shadow-lg"
			use:clickOutside
			on:outclick={handleClose}
		>
			<div>
				<slot name="header">
					<h1 class="text-2xl font-semibold text-slate-100">{title}</h1>
				</slot>
			</div>
			<div>
				<slot name="body" />
			</div>
			<div class="flex justify-end">
				<slot name="footer" />
			</div>
		</div>
	</div>
{/if}
